FROM node:18-alpine
ARG BUILD_DATE
ARG VERSION
ARG VCS_REF
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.name="node-gyp" \
      org.label-schema.version=${VERSION} \
      org.label-schema.build-date=${BUILD_DATE} \
      org.label-schema.description="node-gyp with toolchain on the NodeJS image" \
      org.label-schema.url="https://github.com/nodejs/node-gyp/" \
      org.label-schema.vcs-url="https://github.com/daotl/node-gyp-docker/" \
      org.label-schema.vcs-ref=${VCS_REF}
ENV NODE_GYP_VERSION=${VERSION}
ENV HOME=/root
# `pnpm` needs `ssh`, `turborepo` needs `libc6-compat`
# `pnpm setup` in Docker: https://github.com/pnpm/pnpm/issues/4495#issuecomment-1297010385
RUN apk add --no-cache python3 make g++ git openssh-client libc6-compat && \
    yarn global add node-gyp@${VERSION} && \
    yarn cache clean && \
    node-gyp help && \
    mkdir $HOME/.cache && \
    chown -R node:node $HOME && \
    npm install -g pnpm && \
    SHELL=bash pnpm setup && \
    source ~/.bashrc
USER root
VOLUME $HOME/.cache
WORKDIR $HOME
CMD ["sh"]
