ARG NODEJS_VERSION=lts
ARG BUILD_DATE
ARG VERSION
ARG VCS_REF


FROM daotl/node-gyp:${VERSION}-node-${NODEJS_VERSION}-root-git-pnpm-alpine

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.name="node-gyp" \
      org.label-schema.version=${VERSION} \
      org.label-schema.build-date=${BUILD_DATE} \
      org.label-schema.description="node-gyp with toolchain on the NodeJS image" \
      org.label-schema.url="https://github.com/nodejs/node-gyp/" \
      org.label-schema.vcs-url="https://github.com/daotl/node-gyp-docker/" \
      org.label-schema.vcs-ref=${VCS_REF}

# `turborepo` needs `libc6-compat`
RUN apk add --no-cache libc6-compat
